spring.application.name=Okena
spring.datasource.url=jdbc:postgresql://${DB_HOST_POST}/okena
spring.datasource.username=${DB_USER_POST}
spring.datasource.password=${DB_PASSWORD_POST}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=otg.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update